// NPC DEFINITIONS - Part 1
export const NPCS_DEF=[
  {id:"mira",n:"Mira",r:"House Servant",em:"👩",l:20,t:15,a:0,li:true,un:true,
   level:1,exp:0,expNext:100,
   baseStats:{str:5,agi:8,end:6,mor:7},
   growths:{str:"C",agi:"B",end:"C",mor:"A"},
   showNums:false,
   traits:[
     {n:"Sharp Eyes",d:"Notices everything. Trust reveals more event info.",tp:"positive",fixed:true},
     {n:"Resilient",d:"Recovers from injuries 50% faster.",tp:"positive"},
     {n:"Cautious",d:"Never takes unnecessary risks.",tp:"neutral"},
   ],
   milestones:{
     10:{upgrade:{from:"Sharp Eyes",to:{n:"Piercing Gaze",d:"Nothing escapes her. All hidden events revealed.",tp:"positive",fixed:true}}},
     20:{upgrade:{from:"Resilient",to:{n:"Unshakeable",d:"Immune to loyalty drops from disasters.",tp:"positive"}}},
     30:{op:{n:"Aether Touched",d:"All stats +15% near ruins.",tp:"op"}},
   },
   equipment:{weapon:null,armour:null,accessory:null},
   urb:null,ur:null},
  {id:"aldric",n:"Aldric",r:"Head Farmer",em:"👨‍🌾",l:12,t:10,a:null,li:false,un:true,
   level:1,exp:0,expNext:100,
   baseStats:{str:9,agi:3,end:12,mor:8},
   growths:{str:"B",agi:"D",end:"S",mor:"A"},
   showNums:false,
   traits:[
     {n:"Knows the Land",d:"Farming output +20%. Knows Embervale's soil secrets.",tp:"positive",fixed:true},
     {n:"Hardworking",d:"Output +15%.",tp:"positive"},
     {n:"Resentful",d:"Loyalty gains halved.",tp:"negative"},
   ],
   milestones:{
     10:{upgrade:{from:"Knows the Land",to:{n:"Master of the Land",d:"Farming output +50%. Can predict harvests.",tp:"positive",fixed:true}}},
     20:{upgrade:{from:"Hardworking",to:{n:"Tireless",d:"Never needs rest. Output +30% always.",tp:"positive"}}},
     30:{op:{n:"Unbreakable",d:"Cannot be killed in combat. Survives with 1 HP.",tp:"op"}},
   },
   equipment:{weapon:null,armour:null,accessory:null},
   urb:null,ur:null},
  {id:"zara",n:"Zara",r:"Forest Dweller",em:"🧝",l:0,t:0,a:0,li:true,un:false,
   level:1,exp:0,expNext:100,
   baseStats:{str:6,agi:14,end:7,mor:10},
   growths:{str:"C",agi:"S",end:"C",mor:"B"},
   showNums:false,
   traits:[
     {n:"Nature's Bond",d:"Communicates with creatures. Exploration SP +25%.",tp:"positive",fixed:true},
     {n:"Perceptive",d:"Spots ambushes. -30% surprise chance.",tp:"positive"},
     {n:"Exiled",d:"Works better alone (+15% solo tasks).",tp:"neutral"},
   ],
   milestones:{
     10:{upgrade:{from:"Nature's Bond",to:{n:"Forest Queen",d:"All forest creatures allied. Can summon aid once per season.",tp:"positive",fixed:true}}},
     20:{upgrade:{from:"Perceptive",to:{n:"Sixth Sense",d:"Always acts first. Cannot be ambushed.",tp:"positive"}}},
     30:{op:{n:"Aether Touched",d:"All stats +15% near ruins.",tp:"op"}},
   },
   equipment:{weapon:null,armour:null,accessory:null},
   urb:"woodcutter",ur:null},
  {id:"lyra",n:"Lyra",r:"Merchant's Daughter",em:"👩‍💼",l:0,t:0,a:0,li:true,un:false,
   level:1,exp:0,expNext:100,
   baseStats:{str:4,agi:9,end:5,mor:8},
   growths:{str:"D",agi:"B",end:"C",mor:"B"},
   showNums:false,
   traits:[
     {n:"Market Intuition",d:"Always knows best price. Gold income +20%.",tp:"positive",fixed:true},
     {n:"Ambitious",d:"EXP +10% but loyalty harder to maintain.",tp:"neutral"},
     {n:"Trapped",d:"Conflicted loyalties. Needs trust before full commitment.",tp:"negative"},
   ],
   milestones:{
     10:{upgrade:{from:"Market Intuition",to:{n:"Trade Master",d:"Gold income +40%. Access to rare merchants.",tp:"positive",fixed:true}}},
     20:{upgrade:{from:"Trapped",to:{n:"Her Own Woman",d:"Fully committed. All loyalty penalties removed.",tp:"positive"}}},
     30:{op:{n:"Overclock",d:"Produces 2x in specialty. Needs rest every 3 days.",tp:"op"}},
   },
   equipment:{weapon:null,armour:null,accessory:null},
   urb:"market",ur:null},
  {id:"ser_edwyn",n:"Ser Edwyn",r:"Wandering Knight",em:"⚔️",l:0,t:0,a:null,li:false,un:false,
   level:1,exp:0,expNext:100,
   baseStats:{str:14,agi:8,end:12,mor:6},
   growths:{str:"A",agi:"C",end:"B",mor:"D"},
   showNums:false,
   traits:[
     {n:"Old Techniques",d:"Trains soldiers. Soldier EXP +30%.",tp:"positive",fixed:true},
     {n:"Honorable",d:"Never attacks unarmed. Loyalty immovable.",tp:"positive"},
     {n:"Guilt-ridden",d:"EXP +15% in any combat.",tp:"neutral"},
   ],
   milestones:{
     10:{upgrade:{from:"Old Techniques",to:{n:"Sword Master",d:"All soldiers +20% STR.",tp:"positive",fixed:true}}},
     20:{upgrade:{from:"Guilt-ridden",to:{n:"Redeemed",d:"All stats +10%. Driven by choice, not guilt.",tp:"positive"}}},
     30:{op:{n:"Duellist",d:"1v1: always wins first exchange.",tp:"op"}},
   },
   equipment:{weapon:null,armour:null,accessory:null},
   urb:"barracks",ur:40},
];
