// NPC DEFINITIONS - Part 2
export const NPCS_DEF_PART2=[
  {id:"kaela",n:"Kaela",r:"Adventurer",em:"🗡️",l:0,t:0,a:0,li:true,un:false,
   level:1,exp:0,expNext:100,
   baseStats:{str:10,agi:13,end:8,mor:5},
   growths:{str:"B",agi:"A",end:"C",mor:"E"},
   showNums:false,
   traits:[
     {n:"Combat Veteran",d:"+10% all combat stats. Never surprised.",tp:"positive",fixed:true},
     {n:"Sarcastic",d:"Morale immune to speeches — good and bad.",tp:"neutral"},
     {n:"Loyal for Gold",d:"Requires payment but delivers results.",tp:"neutral"},
   ],
   milestones:{
     10:{upgrade:{from:"Combat Veteran",to:{n:"Battlefield Legend",d:"-20% incoming damage always.",tp:"positive",fixed:true}}},
     20:{upgrade:{from:"Loyal for Gold",to:{n:"Loyal for Real",d:"Fully committed. MOR grows to A tier.",tp:"positive"}}},
     30:{op:{n:"Berserker",d:"Below 30% HP: damage doubles.",tp:"op"}},
   },
   equipment:{weapon:null,armour:null,accessory:null},
   urb:"tavern",ur:null},
  {id:"brother_aldous",n:"Brother Aldous",r:"Fallen Priest",em:"👨‍⚖️",l:0,t:0,a:null,li:false,un:false,
   level:1,exp:0,expNext:100,
   baseStats:{str:3,agi:5,end:6,mor:14},
   growths:{str:"E",agi:"D",end:"C",mor:"S"},
   showNums:false,
   traits:[
     {n:"Forbidden Knowledge",d:"Knows truths about Aether. Unlocks Aether research.",tp:"positive",fixed:true},
     {n:"Observant",d:"+SP on exploration.",tp:"neutral"},
     {n:"Disgraced",d:"Church faction relations -10%.",tp:"negative"},
   ],
   milestones:{
     10:{upgrade:{from:"Forbidden Knowledge",to:{n:"Aether Scholar",d:"Unlocks Tier 2 Aether for Rean.",tp:"positive",fixed:true}}},
     20:{upgrade:{from:"Disgraced",to:{n:"Vindicated",d:"Church relations normalise. Reputation +10.",tp:"positive"}}},
     30:{op:{n:"Aether Touched",d:"All stats +15% near ruins.",tp:"op"}},
   ],
   equipment:{weapon:null,armour:null,accessory:null},
   urb:"tavern",ur:null},
  {id:"seraphine",n:"Seraphine",r:"Young Sister",em:"😇",l:0,t:0,a:0,li:true,un:false,
   level:1,exp:0,expNext:100,
   baseStats:{str:3,agi:6,end:7,mor:15},
   growths:{str:"E",agi:"C",end:"B",mor:"S"},
   showNums:false,
   traits:[
     {n:"Compassionate",d:"All injured serfs recover 30% faster.",tp:"positive",fixed:true},
     {n:"Devout",d:"Church relations +15% always.",tp:"neutral"},
     {n:"Questioning",d:"May unlock unique Aether events.",tp:"neutral"},
   ],
   milestones:{
     10:{upgrade:{from:"Compassionate",to:{n:"Healer",d:"Can treat serious injuries without hospital.",tp:"positive",fixed:true}}},
     20:{upgrade:{from:"Questioning",to:{n:"Enlightened",d:"Unique healing Aether abilities unlock.",tp:"positive"}}},
     30:{op:{n:"Born Leader",d:"All nearby serfs +10% all stats.",tp:"op"}},
   ],
   equipment:{weapon:null,armour:null,accessory:null},
   urb:"chapel",ur:null},
  {id:"isolde",n:"Isolde",r:"Arcane Apprentice",em:"🔮",l:0,t:0,a:0,li:true,un:false,
   level:1,exp:0,expNext:100,
   baseStats:{str:4,agi:7,end:5,mor:12},
   growths:{str:"D",agi:"B",end:"C",mor:"A"},
   showNums:false,
   traits:[
     {n:"Aether Sensitive",d:"Naturally senses Aether. Unlocks shared Aether training.",tp:"positive",fixed:true},
     {n:"Curious",d:"Discovers hidden info. +15 SP on exploration events.",tp:"positive"},
     {n:"Watched",d:"The Order monitors her. Arcana faction -10%.",tp:"negative"},
   ],
   milestones:{
     10:{upgrade:{from:"Aether Sensitive",to:{n:"Aether Reader",d:"Can read Aether imprints on objects and places.",tp:"positive",fixed:true}}},
     20:{upgrade:{from:"Watched",to:{n:"Gone Rogue",d:"Cut ties with the Order. Free. All stats +8%.",tp:"positive"}}},
     30:{op:{n:"Aether Touched",d:"All stats +15% near ruins.",tp:"op"}},
   ],
   equipment:{weapon:null,armour:null,accessory:null},
   urb:null,ur:60},
  {id:"lady_evelyn",n:"Lady Evelyn",r:"Rival's Daughter",em:"👸",l:0,t:0,a:0,li:true,un:false,
   level:1,exp:0,expNext:100,
   baseStats:{str:5,agi:10,end:6,mor:9},
   growths:{str:"C",agi:"B",end:"C",mor:"B"},
   showNums:false,
   traits:[
     {n:"Noble Poise",d:"Reputation +10% in all formal events.",tp:"positive",fixed:true},
     {n:"Secret Agent",d:"Gathers information on enemies. +20 SP/week.",tp:"neutral"},
     {n:"Conflicted",d:"Torn between loyalty to father and to you.",tp:"negative"},
   ],
   milestones:{
     10:{upgrade:{from:"Noble Poise",to:{n:"Royal Presence",d:"Reputation +20% in all events. Opens royal doors.",tp:"positive",fixed:true}}},
     20:{upgrade:{from:"Conflicted",to:{n:"Chosen Side",d:"Chose you. All loyalty from Harwick removed. Full commitment.",tp:"positive"}}},
     30:{op:{n:"Shadow Marked",d:"+25% all combat. -10% loyalty always.",tp:"op"}},
   ],
   equipment:{weapon:null,armour:null,accessory:null},
   urb:null,ur:50},
];
